name: Release library

on:
  release:
    types: [created]

jobs:
  ci_tests:
    uses: ./.github/workflows/ci_tests.yml

  ci_release:
    uses: dsi-hug/actions/.github/workflows/action.yml@v2
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      release: true
