name: Release library

on:
  release:
    types: [created]

permissions:
  id-token: write # Required for NPM Trusted Publishers

jobs:
  ci_release:
    uses: badisi/actions/.github/workflows/action.yml@v4
    with:
      test: true
      build: true
      release: true
